[FusionRings]
git-tree-sha1 = "edc377613f3d2a2e11130c9179b5727fad4404c9"

    [[FusionRings.download]]
      url    = "https://github.com/anyonwiki/AnyonWikiDatabase/raw/refs/heads/main/AlgebraicStructures/FusionRings.tar.gz"
      sha256 = "e8a67c1b5e8ba1ec80805e379fd5619453f0728a17e1c9733ef666a3ae52b6fe"

[AlgebraicNumbers]
git-tree-sha1 = "95afe4d9385eefa279696e4825efbb0ee5e331ae"

    [[AlgebraicNumbers.download]]
    url    = "https://github.com/anyonwiki/AnyonWikiDatabase/raw/refs/heads/main/SupportingData/AlgebraicNumbers.tar.gz"
    sha256 = "f2c4d37d5959b2b9db3aa51dc01276ccd6eed33afa865e908823914c9c4ce88d"
