[FusionRings]
git-tree-sha1 = "89c48c5e36fff5bcf8f8624122a6750845637c06"

    [[FusionRings.download]]
      url    = "https://github.com/anyonwiki/AnyonWikiDatabase/blob/main/AlgebraicStructures/FusionRings.tar.gz"
      sha256 = "737ab9515431bbd37c64f583f08104227c1f36385a5041d0bd07047acae58e97"

[AlgebraicNumbers]
git-tree-sha1 = "862239c7cdbdcffd8387213d22faf45f25920eb7"

    [[AlgebraicNumbers.download]]
    url    = "https://github.com/anyonwiki/AnyonWikiDatabase/blob/main/SupportingData/AlgebraicNumbers.tar.gz"
    sha256 = "541abfd6044e38eead5b61b6fbc12a51e96d3fe96a65ec719962e16986401c1d"
