name = "FusionRings"
uuid = "750f8238-3f78-4e88-85d4-6e65b940c8ab"
authors = ["gert-vercleyen <gert.vercleyen@protonmail.com>", "Szagha02"]
version = "1.0.0-DEV"

[compat]
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
